import type { Category, Product, GemVariant, GemImage } from "@/types";

const img = (seed: string, id: string): GemImage => ({
  id,
  variant_id: `var-${seed}`,
  url: `https://picsum.photos/seed/${seed}/800/600`,
  alt_text: seed,
  sort_order: 0,
  is_primary: true,
  created_at: "2026-01-01T00:00:00Z",
});

const localImg = (path: string, alt: string, id: string): GemImage => ({
  id,
  variant_id: `var-${id}`,
  url: path,
  alt_text: alt,
  sort_order: 0,
  is_primary: true,
  created_at: "2026-01-01T00:00:00Z",
});

export const MOCK_CATEGORIES: Category[] = [
  { id: "cat-1", name: "Ruby", slug: "ruby", description: "Natural rubies from Burma, Mozambique and Sri Lanka", image_url: "https://picsum.photos/seed/ruby-cat/600/400", sort_order: 1, is_active: true, created_at: "2026-01-01T00:00:00Z" },
  { id: "cat-2", name: "Sapphire", slug: "sapphire", description: "Blue, pink and fancy sapphires from Ceylon and Kashmir", image_url: "https://picsum.photos/seed/sapphire-cat/600/400", sort_order: 2, is_active: true, created_at: "2026-01-01T00:00:00Z" },
  { id: "cat-3", name: "Emerald", slug: "emerald", description: "Colombian and Zambian emeralds", image_url: "https://picsum.photos/seed/emerald-cat/600/400", sort_order: 3, is_active: true, created_at: "2026-01-01T00:00:00Z" },
  { id: "cat-4", name: "Alexandrite", slug: "alexandrite", description: "Color-change alexandrite from Brazil and Russia", image_url: "https://picsum.photos/seed/alex-cat/600/400", sort_order: 4, is_active: true, created_at: "2026-01-01T00:00:00Z" },
  { id: "cat-5", name: "Tourmaline", slug: "tourmaline", description: "Paraiba, rubellite and chrome tourmalines", image_url: "https://picsum.photos/seed/tourm-cat/600/400", sort_order: 5, is_active: true, created_at: "2026-01-01T00:00:00Z" },
  { id: "cat-6", name: "Spinel", slug: "spinel", description: "Burmese and Tanzanian spinels in vivid hues", image_url: "https://picsum.photos/seed/spinel-cat/600/400", sort_order: 6, is_active: true, created_at: "2026-01-01T00:00:00Z" },
  { id: "cat-7", name: "Diamond", slug: "diamond", description: "Natural diamonds in round, cushion, pear, oval and fancy cuts", image_url: "/images/diamond_round.png", sort_order: 7, is_active: true, created_at: "2026-01-01T00:00:00Z" },
];

const makeVariant = (
  id: string,
  productId: string,
  sku: string,
  price: number,
  shape: string,
  carat: number,
  color: string,
  origin: string,
  treatment: string,
  imageSeed: string,
  overrides?: Partial<GemVariant>
): GemVariant => ({
  id,
  product_id: productId,
  sku,
  price,
  stock_qty: 1,
  shape,
  carat_weight: carat,
  color,
  color_grade: "AAA",
  clarity: "Eye-clean",
  treatment,
  origin,
  cut_grade: "Excellent",
  length_mm: carat * 3.8,
  width_mm: carat * 3.0,
  depth_mm: carat * 2.2,
  is_active: true,
  created_at: "2026-01-01T00:00:00Z",
  images: [img(imageSeed, `img-${id}`)],
  ...overrides,
});

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "prod-1",
    name: "Burmese Ruby",
    slug: "burmese-ruby-oval-2-35ct",
    description: "A stunning unheated Burmese ruby displaying pigeon blood red color with exceptional saturation. Certified by Gübelin Gem Lab. One of the rarest combinations of origin and treatment status available in the market today.",
    category_id: "cat-1",
    is_active: true,
    is_featured: true,
    meta_title: "Burmese Ruby 2.35ct Oval — Gemstone Empire",
    meta_description: "Unheated Burmese ruby, pigeon blood, 2.35ct oval. Gübelin certified.",
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-01-01T00:00:00Z",
    category: MOCK_CATEGORIES[0],
    variants: [
      makeVariant("var-1", "prod-1", "RUB-OV-235", 4200, "oval", 2.35, "Pigeon Blood Red", "Burma", "Unheated", "gem-ruby-oval"),
    ],
  },
  {
    id: "prod-2",
    name: "Ceylon Blue Sapphire",
    slug: "ceylon-blue-sapphire-cushion-3-12ct",
    description: "Royal blue Ceylon sapphire with outstanding transparency and excellent cut. The velvety blue hue characteristic of the finest Sri Lankan material. Minor heat treatment only.",
    category_id: "cat-2",
    is_active: true,
    is_featured: true,
    meta_title: "Ceylon Sapphire 3.12ct Cushion — Gemstone Empire",
    meta_description: "Blue Ceylon sapphire 3.12ct cushion cut, royal blue, minor heat only.",
    created_at: "2026-01-10T00:00:00Z",
    updated_at: "2026-01-10T00:00:00Z",
    category: MOCK_CATEGORIES[1],
    variants: [
      makeVariant("var-2", "prod-2", "SAP-CU-312", 3800, "cushion", 3.12, "Royal Blue", "Ceylon (Sri Lanka)", "Heat", "gem-sapphire-blue"),
    ],
  },
  {
    id: "prod-3",
    name: "Colombian Emerald",
    slug: "colombian-emerald-pear-1-85ct",
    description: "Vivid green Colombian emerald with the characteristic warm green hue prized by collectors. Minor oil treatment as is standard for the finest Colombian material. Excellent transparency for the species.",
    category_id: "cat-3",
    is_active: true,
    is_featured: true,
    meta_title: "Colombian Emerald 1.85ct Pear — Gemstone Empire",
    meta_description: "Colombian emerald 1.85ct pear shape, vivid green, minor oil.",
    created_at: "2026-01-15T00:00:00Z",
    updated_at: "2026-01-15T00:00:00Z",
    category: MOCK_CATEGORIES[2],
    variants: [
      makeVariant("var-3", "prod-3", "EME-PE-185", 2900, "pear", 1.85, "Vivid Green", "Colombia", "Minor Oil", "gem-emerald-green"),
    ],
  },
  {
    id: "prod-4",
    name: "Paraiba Tourmaline",
    slug: "paraiba-tourmaline-oval-1-45ct",
    description: "Exceptional neon blue-green Paraiba tourmaline from the original Brazilian deposit. The electric luminescence is caused by copper and manganese traces found exclusively in Paraiba state. Extremely rare at this size.",
    category_id: "cat-5",
    is_active: true,
    is_featured: true,
    meta_title: "Paraiba Tourmaline 1.45ct Oval — Gemstone Empire",
    meta_description: "Brazilian Paraiba tourmaline 1.45ct, neon blue-green, copper-bearing.",
    created_at: "2026-01-20T00:00:00Z",
    updated_at: "2026-01-20T00:00:00Z",
    category: MOCK_CATEGORIES[4],
    variants: [
      makeVariant("var-4", "prod-4", "PAR-OV-145", 8500, "oval", 1.45, "Neon Blue-Green", "Brazil (Paraiba)", "Heat", "gem-paraiba-teal"),
    ],
  },
  {
    id: "prod-5",
    name: "Burmese Red Spinel",
    slug: "burmese-red-spinel-octagon-2-80ct",
    description: "Natural unheated red spinel from Mogok, Burma — the historic capital of fine gemstones. Vivid red color rivaling the finest rubies, with the advantage of being completely unheated. Increasingly sought after by collectors.",
    category_id: "cat-6",
    is_active: true,
    is_featured: true,
    meta_title: "Burmese Red Spinel 2.80ct — Gemstone Empire",
    meta_description: "Unheated Burmese red spinel 2.80ct octagon, Mogok origin.",
    created_at: "2026-01-25T00:00:00Z",
    updated_at: "2026-01-25T00:00:00Z",
    category: MOCK_CATEGORIES[5],
    variants: [
      makeVariant("var-5", "prod-5", "SPI-OC-280", 1800, "octagon", 2.80, "Vivid Red", "Burma (Mogok)", "Unheated", "gem-spinel-red"),
    ],
  },
  {
    id: "prod-6",
    name: "Brazilian Alexandrite",
    slug: "brazilian-alexandrite-round-0-95ct",
    description: "Remarkable color-change alexandrite showing a distinct shift from teal green in daylight to purplish-red under incandescent light. Strong color change of approximately 70%. Brazilian origin verified.",
    category_id: "cat-4",
    is_active: true,
    is_featured: true,
    meta_title: "Brazilian Alexandrite 0.95ct — Gemstone Empire",
    meta_description: "Brazilian alexandrite 0.95ct round, 70% color change, daylight to incandescent.",
    created_at: "2026-02-01T00:00:00Z",
    updated_at: "2026-02-01T00:00:00Z",
    category: MOCK_CATEGORIES[3],
    variants: [
      makeVariant("var-6", "prod-6", "ALX-RD-095", 6200, "round", 0.95, "Green / Purplish-Red", "Brazil", "Unheated", "gem-alexandrite-green"),
    ],
  },
  {
    id: "prod-7",
    name: "Pink Sapphire",
    slug: "pink-sapphire-marquise-2-10ct",
    description: "Feminine hot pink sapphire from Sri Lanka displaying exceptional saturation. The marquise cut maximises the colour yield and creates an elegant elongated silhouette. Very good clarity with no eye-visible inclusions.",
    category_id: "cat-2",
    is_active: true,
    is_featured: false,
    created_at: "2026-02-05T00:00:00Z",
    updated_at: "2026-02-05T00:00:00Z",
    category: MOCK_CATEGORIES[1],
    variants: [
      makeVariant("var-7", "prod-7", "SAP-MQ-210", 2200, "marquise", 2.10, "Hot Pink", "Ceylon (Sri Lanka)", "Heat", "gem-sapphire-pink"),
    ],
  },
  {
    id: "prod-8",
    name: "Mozambique Ruby",
    slug: "mozambique-ruby-cushion-1-62ct",
    description: "Deep red Mozambique ruby with excellent transparency and strong fluorescence under UV light. Heat treated to industry standard to improve clarity. An affordable entry point into investment-grade rubies.",
    category_id: "cat-1",
    is_active: true,
    is_featured: false,
    created_at: "2026-02-10T00:00:00Z",
    updated_at: "2026-02-10T00:00:00Z",
    category: MOCK_CATEGORIES[0],
    variants: [
      makeVariant("var-8", "prod-8", "RUB-CU-162", 1950, "cushion", 1.62, "Deep Red", "Mozambique", "Heat", "gem-ruby-cushion"),
    ],
  },
  {
    id: "prod-9",
    name: "Teal Sapphire",
    slug: "teal-sapphire-oval-2-55ct",
    description: "Modern teal sapphire with a unique blue-green colour highly sought after by contemporary jewellers. Parti-colour effect visible when the stone is rotated. Unheated, with GIA report confirming natural origin.",
    category_id: "cat-2",
    is_active: true,
    is_featured: false,
    created_at: "2026-02-15T00:00:00Z",
    updated_at: "2026-02-15T00:00:00Z",
    category: MOCK_CATEGORIES[1],
    variants: [
      makeVariant("var-9", "prod-9", "SAP-OV-255", 1650, "oval", 2.55, "Teal Blue-Green", "Australia", "Unheated", "gem-teal-sapphire"),
    ],
  },
  {
    id: "prod-10",
    name: "Chrome Tourmaline",
    slug: "chrome-tourmaline-emerald-1-20ct",
    description: "Vivid grass-green chrome tourmaline from Tanzania, coloured by chromium — the same element that gives emeralds their green. Significantly more transparent than emerald at a fraction of the price.",
    category_id: "cat-5",
    is_active: true,
    is_featured: false,
    created_at: "2026-02-20T00:00:00Z",
    updated_at: "2026-02-20T00:00:00Z",
    category: MOCK_CATEGORIES[4],
    variants: [
      makeVariant("var-10", "prod-10", "TOU-EM-120", 780, "emerald", 1.20, "Vivid Green", "Tanzania", "Unheated", "gem-chrome-tourmaline"),
    ],
  },
  {
    id: "prod-11",
    name: "Kashmir Sapphire",
    slug: "kashmir-sapphire-oval-1-05ct",
    description: "Exceptional cornflower blue Kashmir sapphire displaying the famous velvety appearance caused by silk inclusions scattering light. Kashmir material commands the highest premiums of any sapphire origin. AGL certified.",
    category_id: "cat-2",
    is_active: true,
    is_featured: false,
    created_at: "2026-02-25T00:00:00Z",
    updated_at: "2026-02-25T00:00:00Z",
    category: MOCK_CATEGORIES[1],
    variants: [
      makeVariant("var-11", "prod-11", "SAP-OV-105K", 12500, "oval", 1.05, "Cornflower Blue", "Kashmir", "Unheated", "gem-kashmir-sapphire"),
    ],
  },
  {
    id: "prod-12",
    name: "Rubellite Tourmaline",
    slug: "rubellite-tourmaline-trillion-1-88ct",
    description: "Intense pinkish-red rubellite from Mozambique with exceptional saturation meeting the strict criteria for the rubellite designation. The trillion cut accentuates the depth of colour and adds geometric drama.",
    category_id: "cat-5",
    is_active: true,
    is_featured: false,
    created_at: "2026-03-01T00:00:00Z",
    updated_at: "2026-03-01T00:00:00Z",
    category: MOCK_CATEGORIES[4],
    variants: [
      makeVariant("var-12", "prod-12", "TOU-TR-188", 1100, "trillion", 1.88, "Vivid Pinkish-Red", "Mozambique", "Unheated", "gem-rubellite"),
    ],
  },
  // ─── Diamonds ──────────────────────────────────────────────
  {
    id: "prod-13",
    name: "Round Brilliant Diamond",
    slug: "round-brilliant-diamond-1-52ct",
    description: "A stunning GIA-certified round brilliant cut diamond with exceptional fire and scintillation. D color, VVS1 clarity — the pinnacle of diamond quality. Triple-excellent cut grade ensures maximum light performance and brilliance.",
    category_id: "cat-7",
    is_active: true,
    is_featured: true,
    meta_title: "Round Brilliant Diamond 1.52ct D VVS1 — Gemstone Empire",
    meta_description: "GIA certified round brilliant diamond 1.52ct, D color, VVS1 clarity, triple excellent.",
    created_at: "2026-03-05T00:00:00Z",
    updated_at: "2026-03-05T00:00:00Z",
    category: MOCK_CATEGORIES[6],
    variants: [
      {
        ...makeVariant("var-13", "prod-13", "DIA-RD-152", 18500, "round", 1.52, "D (Colorless)", "Botswana", "None", "diamond-round"),
        clarity: "VVS1",
        color_grade: "D",
        cut_grade: "Triple Excellent",
        length_mm: 7.35,
        width_mm: 7.38,
        depth_mm: 4.56,
        images: [localImg("/images/diamond_round.png", "Round Brilliant Diamond 1.52ct", "img-var-13")],
      },
    ],
  },
  {
    id: "prod-14",
    name: "Cushion Cut Diamond",
    slug: "cushion-cut-diamond-2-01ct",
    description: "A magnificent cushion modified brilliant diamond with soft rounded corners and a pillow-like shape. The larger facet pattern creates bold flashes of light. E color with VS1 clarity — an exceptional balance of quality and size.",
    category_id: "cat-7",
    is_active: true,
    is_featured: true,
    meta_title: "Cushion Cut Diamond 2.01ct E VS1 — Gemstone Empire",
    meta_description: "Cushion cut diamond 2.01ct, E color, VS1 clarity, excellent symmetry.",
    created_at: "2026-03-10T00:00:00Z",
    updated_at: "2026-03-10T00:00:00Z",
    category: MOCK_CATEGORIES[6],
    variants: [
      {
        ...makeVariant("var-14", "prod-14", "DIA-CU-201", 22800, "cushion", 2.01, "E (Colorless)", "South Africa", "None", "diamond-cushion"),
        clarity: "VS1",
        color_grade: "E",
        cut_grade: "Excellent",
        length_mm: 7.12,
        width_mm: 6.85,
        depth_mm: 4.68,
        images: [localImg("/images/diamond_cushion.png", "Cushion Cut Diamond 2.01ct", "img-var-14")],
      },
    ],
  },
  {
    id: "prod-15",
    name: "Pear Shape Diamond",
    slug: "pear-shape-diamond-1-75ct",
    description: "An elegant pear-shaped brilliant diamond combining the best of round and marquise cuts. The teardrop silhouette makes it a favourite for pendants and solitaire rings. F color, VS2 clarity with excellent polish.",
    category_id: "cat-7",
    is_active: true,
    is_featured: false,
    meta_title: "Pear Shape Diamond 1.75ct F VS2 — Gemstone Empire",
    meta_description: "Pear shape diamond 1.75ct, F color, VS2 clarity.",
    created_at: "2026-03-15T00:00:00Z",
    updated_at: "2026-03-15T00:00:00Z",
    category: MOCK_CATEGORIES[6],
    variants: [
      {
        ...makeVariant("var-15", "prod-15", "DIA-PE-175", 14200, "pear", 1.75, "F (Colorless)", "Russia", "None", "diamond-pear"),
        clarity: "VS2",
        color_grade: "F",
        cut_grade: "Excellent",
        length_mm: 9.82,
        width_mm: 6.41,
        depth_mm: 3.98,
        images: [localImg("/images/diamond_pear.png", "Pear Shape Diamond 1.75ct", "img-var-15")],
      },
    ],
  },
  {
    id: "prod-16",
    name: "Emerald Cut Diamond",
    slug: "emerald-cut-diamond-2-33ct",
    description: "A sophisticated emerald cut diamond with the distinctive step-cut faceting that creates a hall-of-mirrors effect. The open table showcases the stone's exceptional clarity. D color, IF (Internally Flawless) — museum-quality.",
    category_id: "cat-7",
    is_active: true,
    is_featured: false,
    meta_title: "Emerald Cut Diamond 2.33ct D IF — Gemstone Empire",
    meta_description: "Emerald cut diamond 2.33ct, D color, Internally Flawless clarity.",
    created_at: "2026-03-20T00:00:00Z",
    updated_at: "2026-03-20T00:00:00Z",
    category: MOCK_CATEGORIES[6],
    variants: [
      {
        ...makeVariant("var-16", "prod-16", "DIA-EM-233", 35600, "emerald", 2.33, "D (Colorless)", "Botswana", "None", "diamond-emerald"),
        clarity: "IF",
        color_grade: "D",
        cut_grade: "Excellent",
        length_mm: 8.72,
        width_mm: 6.34,
        depth_mm: 4.25,
        images: [localImg("/images/diamond_emerald_cut.png", "Emerald Cut Diamond 2.33ct", "img-var-16")],
      },
    ],
  },
  {
    id: "prod-17",
    name: "Oval Brilliant Diamond",
    slug: "oval-brilliant-diamond-1-30ct",
    description: "A beautifully proportioned oval brilliant diamond with an elongated shape that appears larger than its carat weight. The modified brilliant faceting delivers outstanding fire and brilliance. G color, VVS2 clarity.",
    category_id: "cat-7",
    is_active: true,
    is_featured: false,
    meta_title: "Oval Brilliant Diamond 1.30ct G VVS2 — Gemstone Empire",
    meta_description: "Oval brilliant diamond 1.30ct, G color, VVS2 clarity.",
    created_at: "2026-03-25T00:00:00Z",
    updated_at: "2026-03-25T00:00:00Z",
    category: MOCK_CATEGORIES[6],
    variants: [
      {
        ...makeVariant("var-17", "prod-17", "DIA-OV-130", 9800, "oval", 1.30, "G (Near Colorless)", "Canada", "None", "diamond-oval"),
        clarity: "VVS2",
        color_grade: "G",
        cut_grade: "Excellent",
        length_mm: 8.15,
        width_mm: 5.92,
        depth_mm: 3.71,
        images: [localImg("/images/diamond_oval.png", "Oval Brilliant Diamond 1.30ct", "img-var-17")],
      },
    ],
  },
  {
    id: "prod-18",
    name: "Marquise Diamond",
    slug: "marquise-diamond-0-98ct",
    description: "A regal marquise brilliant diamond with an elongated boat shape and pointed ends. The marquise cut maximises carat weight, making it appear considerably larger than other shapes at the same weight. E color, VS1 clarity.",
    category_id: "cat-7",
    is_active: true,
    is_featured: false,
    meta_title: "Marquise Diamond 0.98ct E VS1 — Gemstone Empire",
    meta_description: "Marquise diamond 0.98ct, E color, VS1 clarity.",
    created_at: "2026-03-28T00:00:00Z",
    updated_at: "2026-03-28T00:00:00Z",
    category: MOCK_CATEGORIES[6],
    variants: [
      {
        ...makeVariant("var-18", "prod-18", "DIA-MQ-098", 7200, "marquise", 0.98, "E (Colorless)", "South Africa", "None", "diamond-marquise"),
        clarity: "VS1",
        color_grade: "E",
        cut_grade: "Very Good",
        length_mm: 10.12,
        width_mm: 5.08,
        depth_mm: 3.15,
        images: [localImg("/images/diamond_marquise.png", "Marquise Diamond 0.98ct", "img-var-18")],
      },
    ],
  },
];

export const FEATURED_PRODUCTS = MOCK_PRODUCTS.filter((p) => p.is_featured);

export const MOCK_REVIEWS = [
  {
    id: "rev-1",
    author: "James Richardson",
    location: "New York, USA",
    rating: 5,
    title: "Exceptional Burmese Ruby",
    body: "Purchased a 2ct Burmese ruby for an engagement ring. The colour saturation is remarkable — true pigeon blood red. Arrived beautifully packaged with all certificates. Customer service was outstanding throughout.",
    product: "Burmese Ruby 2.35ct Oval",
    date: "2026-04-12",
    verified: true,
  },
  {
    id: "rev-2",
    author: "Sarah Chen",
    location: "Vancouver, Canada",
    rating: 5,
    title: "Beautiful Ceylon Sapphire",
    body: "The sapphire exceeded my expectations. The royal blue colour is stunning and the stone has excellent transparency. Fast international shipping with full insurance. Will definitely buy again.",
    product: "Ceylon Blue Sapphire 3.12ct",
    date: "2026-03-28",
    verified: true,
  },
  {
    id: "rev-3",
    author: "Marco Bellini",
    location: "Milan, Italy",
    rating: 5,
    title: "Rare Paraiba — Worth Every Penny",
    body: "Finding a genuine Brazilian Paraiba at this quality is nearly impossible. The neon glow is mesmerising and the stone photographs beautifully. Expert gemological knowledge from the team too.",
    product: "Paraiba Tourmaline 1.45ct",
    date: "2026-05-01",
    verified: true,
  },
  {
    id: "rev-4",
    author: "Emma Thompson",
    location: "London, UK",
    rating: 4,
    title: "Gorgeous Emerald for My Collection",
    body: "Colombian emerald with lovely vivid green colour. Minor inclusions as expected for emerald but excellent transparency overall. The pear shape is very elegant. Smooth buying experience.",
    product: "Colombian Emerald 1.85ct",
    date: "2026-02-15",
    verified: true,
  },
  {
    id: "rev-5",
    author: "David Park",
    location: "Seoul, South Korea",
    rating: 5,
    title: "Investment Grade Spinel",
    body: "Burmese red spinel unheated — exactly as described. The vivid red rivals fine rubies at a fraction of the price. Comes with a detailed gemological report. Trusted dealer with genuine stones.",
    product: "Burmese Red Spinel 2.80ct",
    date: "2026-04-05",
    verified: true,
  },
  {
    id: "rev-6",
    author: "Lisa Müller",
    location: "Zurich, Switzerland",
    rating: 5,
    title: "Amazing Alexandrite Color Change",
    body: "The colour change on this alexandrite is spectacular — vivid green to purplish red. At nearly 1ct this is a serious collector stone. Documentation and provenance all verified. Highly recommended.",
    product: "Brazilian Alexandrite 0.95ct",
    date: "2026-03-10",
    verified: true,
  },
  {
    id: "rev-7",
    author: "Katarina Petrova",
    location: "Prague, Czech Republic",
    rating: 5,
    title: "Stunning Color and Clarity",
    body: "The pink sapphire is absolutely breathtaking. Very fast shipping, well packed, and the certification was complete. Highly recommended dealer!",
    product: "Pink Sapphire 2.10ct Marquise",
    date: "2026-05-10",
    verified: true,
  },
  {
    id: "rev-8",
    author: "Hiroshi Tanaka",
    location: "Tokyo, Japan",
    rating: 5,
    title: "Perfect Cut and Hue",
    body: "Very fine blue sapphire from Ceylon. Cut is excellent and Hue is perfectly royal blue. Standard certificate was verified online. Reliable vendor.",
    product: "Ceylon Blue Sapphire 3.12ct",
    date: "2026-05-18",
    verified: true,
  },
  {
    id: "rev-9",
    author: "Arthur Pendelton",
    location: "Boston, USA",
    rating: 5,
    title: "Verified Natural Gemstone",
    body: "The red spinel shows gorgeous sparkle and fiery red light. This is my second purchase from Gemstone Empire, and I am extremely satisfied with their speed and authenticity.",
    product: "Burmese Red Spinel 2.80ct",
    date: "2026-05-24",
    verified: true,
  },
];

