import type { Category, Product, GemVariant, GemImage } from "@/types";

const img = (seed: string, id: string): GemImage => ({
  id,
  variant_id: `var-${seed}`,
  url: `https://picsum.photos/seed/${seed}/800/600`,
  alt_text: seed,
  sort_order: 0,
  is_primary: true,
  created_at: "2026-01-01T00:00:00Z",
});

export const MOCK_CATEGORIES: Category[] = [
  { id: "cat-1", name: "Ruby", slug: "ruby", description: "Natural rubies from Burma, Mozambique and Sri Lanka", image_url: "https://picsum.photos/seed/ruby-cat/600/400", sort_order: 1, is_active: true, created_at: "2026-01-01T00:00:00Z" },
  { id: "cat-2", name: "Sapphire", slug: "sapphire", description: "Blue, pink and fancy sapphires from Ceylon and Kashmir", image_url: "https://picsum.photos/seed/sapphire-cat/600/400", sort_order: 2, is_active: true, created_at: "2026-01-01T00:00:00Z" },
  { id: "cat-3", name: "Emerald", slug: "emerald", description: "Colombian and Zambian emeralds", image_url: "https://picsum.photos/seed/emerald-cat/600/400", sort_order: 3, is_active: true, created_at: "2026-01-01T00:00:00Z" },
  { id: "cat-4", name: "Alexandrite", slug: "alexandrite", description: "Color-change alexandrite from Brazil and Russia", image_url: "https://picsum.photos/seed/alex-cat/600/400", sort_order: 4, is_active: true, created_at: "2026-01-01T00:00:00Z" },
  { id: "cat-5", name: "Tourmaline", slug: "tourmaline", description: "Paraiba, rubellite and chrome tourmalines", image_url: "https://picsum.photos/seed/tourm-cat/600/400", sort_order: 5, is_active: true, created_at: "2026-01-01T00:00:00Z" },
  { id: "cat-6", name: "Spinel", slug: "spinel", description: "Burmese and Tanzanian spinels in vivid hues", image_url: "https://picsum.photos/seed/spinel-cat/600/400", sort_order: 6, is_active: true, created_at: "2026-01-01T00:00:00Z" },
];

const makeVariant = (
  id: string,
  productId: string,
  sku: string,
  price: number,
  shape: string,
  carat: number,
  color: string,
  origin: string,
  treatment: string,
  imageSeed: string,
  overrides?: Partial<GemVariant>
): GemVariant => ({
  id,
  product_id: productId,
  sku,
  price,
  stock_qty: 1,
  shape,
  carat_weight: carat,
  color,
  color_grade: "AAA",
  clarity: "Eye-clean",
  treatment,
  origin,
  cut_grade: "Excellent",
  length_mm: carat * 3.8,
  width_mm: carat * 3.0,
  depth_mm: carat * 2.2,
  is_active: true,
  created_at: "2026-01-01T00:00:00Z",
  images: [img(imageSeed, `img-${id}`)],
  ...overrides,
});

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "prod-1",
    name: "Burmese Ruby",
    slug: "burmese-ruby-oval-2-35ct",
    description: "A stunning unheated Burmese ruby displaying pigeon blood red color with exceptional saturation. Certified by Gübelin Gem Lab. One of the rarest combinations of origin and treatment status available in the market today.",
    category_id: "cat-1",
    is_active: true,
    is_featured: true,
    meta_title: "Burmese Ruby 2.35ct Oval — Gemstone Empire",
    meta_description: "Unheated Burmese ruby, pigeon blood, 2.35ct oval. Gübelin certified.",
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-01-01T00:00:00Z",
    category: MOCK_CATEGORIES[0],
    variants: [
      makeVariant("var-1", "prod-1", "RUB-OV-235", 4200, "oval", 2.35, "Pigeon Blood Red", "Burma", "Unheated", "gem-ruby-oval"),
    ],
  },
  {
    id: "prod-2",
    name: "Ceylon Blue Sapphire",
    slug: "ceylon-blue-sapphire-cushion-3-12ct",
    description: "Royal blue Ceylon sapphire with outstanding transparency and excellent cut. The velvety blue hue characteristic of the finest Sri Lankan material. Minor heat treatment only.",
    category_id: "cat-2",
    is_active: true,
    is_featured: true,
    meta_title: "Ceylon Sapphire 3.12ct Cushion — Gemstone Empire",
    meta_description: "Blue Ceylon sapphire 3.12ct cushion cut, royal blue, minor heat only.",
    created_at: "2026-01-10T00:00:00Z",
    updated_at: "2026-01-10T00:00:00Z",
    category: MOCK_CATEGORIES[1],
    variants: [
      makeVariant("var-2", "prod-2", "SAP-CU-312", 3800, "cushion", 3.12, "Royal Blue", "Ceylon (Sri Lanka)", "Heat", "gem-sapphire-blue"),
    ],
  },
  {
    id: "prod-3",
    name: "Colombian Emerald",
    slug: "colombian-emerald-pear-1-85ct",
    description: "Vivid green Colombian emerald with the characteristic warm green hue prized by collectors. Minor oil treatment as is standard for the finest Colombian material. Excellent transparency for the species.",
    category_id: "cat-3",
    is_active: true,
    is_featured: true,
    meta_title: "Colombian Emerald 1.85ct Pear — Gemstone Empire",
    meta_description: "Colombian emerald 1.85ct pear shape, vivid green, minor oil.",
    created_at: "2026-01-15T00:00:00Z",
    updated_at: "2026-01-15T00:00:00Z",
    category: MOCK_CATEGORIES[2],
    variants: [
      makeVariant("var-3", "prod-3", "EME-PE-185", 2900, "pear", 1.85, "Vivid Green", "Colombia", "Minor Oil", "gem-emerald-green"),
    ],
  },
  {
    id: "prod-4",
    name: "Paraiba Tourmaline",
    slug: "paraiba-tourmaline-oval-1-45ct",
    description: "Exceptional neon blue-green Paraiba tourmaline from the original Brazilian deposit. The electric luminescence is caused by copper and manganese traces found exclusively in Paraiba state. Extremely rare at this size.",
    category_id: "cat-5",
    is_active: true,
    is_featured: true,
    meta_title: "Paraiba Tourmaline 1.45ct Oval — Gemstone Empire",
    meta_description: "Brazilian Paraiba tourmaline 1.45ct, neon blue-green, copper-bearing.",
    created_at: "2026-01-20T00:00:00Z",
    updated_at: "2026-01-20T00:00:00Z",
    category: MOCK_CATEGORIES[4],
    variants: [
      makeVariant("var-4", "prod-4", "PAR-OV-145", 8500, "oval", 1.45, "Neon Blue-Green", "Brazil (Paraiba)", "Heat", "gem-paraiba-teal"),
    ],
  },
  {
    id: "prod-5",
    name: "Burmese Red Spinel",
    slug: "burmese-red-spinel-octagon-2-80ct",
    description: "Natural unheated red spinel from Mogok, Burma — the historic capital of fine gemstones. Vivid red color rivaling the finest rubies, with the advantage of being completely unheated. Increasingly sought after by collectors.",
    category_id: "cat-6",
    is_active: true,
    is_featured: true,
    meta_title: "Burmese Red Spinel 2.80ct — Gemstone Empire",
    meta_description: "Unheated Burmese red spinel 2.80ct octagon, Mogok origin.",
    created_at: "2026-01-25T00:00:00Z",
    updated_at: "2026-01-25T00:00:00Z",
    category: MOCK_CATEGORIES[5],
    variants: [
      makeVariant("var-5", "prod-5", "SPI-OC-280", 1800, "octagon", 2.80, "Vivid Red", "Burma (Mogok)", "Unheated", "gem-spinel-red"),
    ],
  },
  {
    id: "prod-6",
    name: "Brazilian Alexandrite",
    slug: "brazilian-alexandrite-round-0-95ct",
    description: "Remarkable color-change alexandrite showing a distinct shift from teal green in daylight to purplish-red under incandescent light. Strong color change of approximately 70%. Brazilian origin verified.",
    category_id: "cat-4",
    is_active: true,
    is_featured: true,
    meta_title: "Brazilian Alexandrite 0.95ct — Gemstone Empire",
    meta_description: "Brazilian alexandrite 0.95ct round, 70% color change, daylight to incandescent.",
    created_at: "2026-02-01T00:00:00Z",
    updated_at: "2026-02-01T00:00:00Z",
    category: MOCK_CATEGORIES[3],
    variants: [
      makeVariant("var-6", "prod-6", "ALX-RD-095", 6200, "round", 0.95, "Green / Purplish-Red", "Brazil", "Unheated", "gem-alexandrite-green"),
    ],
  },
  {
    id: "prod-7",
    name: "Pink Sapphire",
    slug: "pink-sapphire-marquise-2-10ct",
    description: "Feminine hot pink sapphire from Sri Lanka displaying exceptional saturation. The marquise cut maximises the colour yield and creates an elegant elongated silhouette. Very good clarity with no eye-visible inclusions.",
    category_id: "cat-2",
    is_active: true,
    is_featured: false,
    created_at: "2026-02-05T00:00:00Z",
    updated_at: "2026-02-05T00:00:00Z",
    category: MOCK_CATEGORIES[1],
    variants: [
      makeVariant("var-7", "prod-7", "SAP-MQ-210", 2200, "marquise", 2.10, "Hot Pink", "Ceylon (Sri Lanka)", "Heat", "gem-sapphire-pink"),
    ],
  },
  {
    id: "prod-8",
    name: "Mozambique Ruby",
    slug: "mozambique-ruby-cushion-1-62ct",
    description: "Deep red Mozambique ruby with excellent transparency and strong fluorescence under UV light. Heat treated to industry standard to improve clarity. An affordable entry point into investment-grade rubies.",
    category_id: "cat-1",
    is_active: true,
    is_featured: false,
    created_at: "2026-02-10T00:00:00Z",
    updated_at: "2026-02-10T00:00:00Z",
    category: MOCK_CATEGORIES[0],
    variants: [
      makeVariant("var-8", "prod-8", "RUB-CU-162", 1950, "cushion", 1.62, "Deep Red", "Mozambique", "Heat", "gem-ruby-cushion"),
    ],
  },
  {
    id: "prod-9",
    name: "Teal Sapphire",
    slug: "teal-sapphire-oval-2-55ct",
    description: "Modern teal sapphire with a unique blue-green colour highly sought after by contemporary jewellers. Parti-colour effect visible when the stone is rotated. Unheated, with GIA report confirming natural origin.",
    category_id: "cat-2",
    is_active: true,
    is_featured: false,
    created_at: "2026-02-15T00:00:00Z",
    updated_at: "2026-02-15T00:00:00Z",
    category: MOCK_CATEGORIES[1],
    variants: [
      makeVariant("var-9", "prod-9", "SAP-OV-255", 1650, "oval", 2.55, "Teal Blue-Green", "Australia", "Unheated", "gem-teal-sapphire"),
    ],
  },
  {
    id: "prod-10",
    name: "Chrome Tourmaline",
    slug: "chrome-tourmaline-emerald-1-20ct",
    description: "Vivid grass-green chrome tourmaline from Tanzania, coloured by chromium — the same element that gives emeralds their green. Significantly more transparent than emerald at a fraction of the price.",
    category_id: "cat-5",
    is_active: true,
    is_featured: false,
    created_at: "2026-02-20T00:00:00Z",
    updated_at: "2026-02-20T00:00:00Z",
    category: MOCK_CATEGORIES[4],
    variants: [
      makeVariant("var-10", "prod-10", "TOU-EM-120", 780, "emerald", 1.20, "Vivid Green", "Tanzania", "Unheated", "gem-chrome-tourmaline"),
    ],
  },
  {
    id: "prod-11",
    name: "Kashmir Sapphire",
    slug: "kashmir-sapphire-oval-1-05ct",
    description: "Exceptional cornflower blue Kashmir sapphire displaying the famous velvety appearance caused by silk inclusions scattering light. Kashmir material commands the highest premiums of any sapphire origin. AGL certified.",
    category_id: "cat-2",
    is_active: true,
    is_featured: false,
    created_at: "2026-02-25T00:00:00Z",
    updated_at: "2026-02-25T00:00:00Z",
    category: MOCK_CATEGORIES[1],
    variants: [
      makeVariant("var-11", "prod-11", "SAP-OV-105K", 12500, "oval", 1.05, "Cornflower Blue", "Kashmir", "Unheated", "gem-kashmir-sapphire"),
    ],
  },
  {
    id: "prod-12",
    name: "Rubellite Tourmaline",
    slug: "rubellite-tourmaline-trillion-1-88ct",
    description: "Intense pinkish-red rubellite from Mozambique with exceptional saturation meeting the strict criteria for the rubellite designation. The trillion cut accentuates the depth of colour and adds geometric drama.",
    category_id: "cat-5",
    is_active: true,
    is_featured: false,
    created_at: "2026-03-01T00:00:00Z",
    updated_at: "2026-03-01T00:00:00Z",
    category: MOCK_CATEGORIES[4],
    variants: [
      makeVariant("var-12", "prod-12", "TOU-TR-188", 1100, "trillion", 1.88, "Vivid Pinkish-Red", "Mozambique", "Unheated", "gem-rubellite"),
    ],
  },
];

export const FEATURED_PRODUCTS = MOCK_PRODUCTS.filter((p) => p.is_featured);
